version: 2
jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.1.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback
            - dependencies-
      - run: yarn install
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
